'use strict';
const $=id=>document.getElementById(id), canvas=$('arena'), ctx=canvas.getContext('2d');
const COLORS=['#dcff62','#ff63b9','#64e7ff','#b693ff','#ffa95e','#fb7376','#70f5bb','#ffffff'];
const keys={}, input={x:0,y:0,dash:false};
let peer=null, hostConn=null, connections=new Map(), isHost=false, practice=false, myId='', room='', state=null, statusTimer=null, lastFrame=performance.now(), lastSend=0, lastRoster='', sound=false, audioCtx=null, lastEvent=0, lastStateAt=0, joinTimeout=null, joystickActive=false;
let localDash=false, mouseTarget=null;
const MAX_PLAYERS=32;
const randCode=()=>Array.from(crypto.getRandomValues(new Uint8Array(6)),x=>'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'[x%32]).join('');
const safeName=n=>String(n||'Bumper').replace(/[\x00-\x1f<>]/g,'').trim().slice(0,16)||'Bumper';
function message(t){$('message').textContent=t;$('roomStatus').textContent=t;}
function beep(f=440,d=.12){if(!sound)return;try{audioCtx??=new (window.AudioContext||window.webkitAudioContext)();audioCtx.resume();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type='sine';o.frequency.setValueAtTime(f,audioCtx.currentTime);o.frequency.exponentialRampToValueAtTime(f*2,audioCtx.currentTime+d);g.gain.setValueAtTime(.07,audioCtx.currentTime);g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+d);o.connect(g);g.connect(audioCtx.destination);o.start();o.stop(audioCtx.currentTime+d);}catch{}}
$('sound').onclick=()=>{sound=!sound;$('sound').textContent=sound?'SOUND ON':'SOUND OFF';$('sound').setAttribute('aria-label',sound?'Disable sound':'Enable sound');beep();};
function setBusy(b){$('create').disabled=b;$('join').disabled=b;$('practice').disabled=b;}
function enter(){clearTimeout(joinTimeout);setBusy(false);document.body.classList.add('playing');$('lobby').hidden=false;$('touchControls').hidden=false;$('roomCode').textContent=practice?'SOLO':room;$('roomLabel').textContent=practice?'PRACTICE ARENA':'ROOM '+room;$('copy').hidden=practice;$('start').hidden=!isHost;$('lobbyTitle').textContent=practice?'WARM UP. WIPE OUT.':'THE GREEN ROOM';message('');window.scrollTo(0,0);renderRoster(true);}
function reset(){clearTimeout(joinTimeout);if(peer)peer.destroy();peer=null;connections.clear();hostConn=null;state=null;isHost=false;practice=false;myId='';lastRoster='';lastEvent=0;document.body.classList.remove('playing');$('lobby').hidden=true;$('touchControls').hidden=true;$('announce').textContent='';$('roomLabel').textContent='THE PERSONAL SPACE ZONE';$('phaseLabel').textContent='LAST ONE IN WINS';setBusy(false);input.x=input.y=0;mouseTarget=null;input.dash=false;joystickActive=false;for(const k in keys)delete keys[k];}
function addPlayer(id,name,bot=false){const used=state.players.map(p=>p.color);state.players.push({id,name:safeName(name),color:COLORS.find(c=>!used.includes(c))||`hsl(${state.players.length*137.508%360} 90% 72%)`,x:450,y:450,vx:0,vy:0,alive:state.phase!=='play',wins:0,cool:0,boost:0,bot,angle:0,inp:{x:0,y:0,dash:false},lastInput:Date.now()});arrange();}
function arrange(){if(state.phase==='play')return;state.players.forEach((p,i)=>{const a=i*2.399963, radius=state.players.length<=8?205:85+190*Math.sqrt(i/Math.max(1,state.players.length-1));p.x=450+Math.cos(a)*radius;p.y=450+Math.sin(a)*radius;p.vx=p.vy=0;});}
function newState(){return {phase:'lobby',players:[],radius:365,clock:0,round:0,winner:'',event:0,eventText:''};}
function setupPeer(id){const p=new Peer(id,{debug:0});peer=p;p.on('error',err=>{if(p!==peer)return;const active=!!state;if(err.type==='peer-unavailable')message('Room not found. Check the code and ask the host to keep their game open.');else if(err.type==='unavailable-id')message('That room code is busy. Please create a room again.');else message('Connection trouble. Try another network, or play with bots.');setBusy(false);if(!active){clearTimeout(joinTimeout);p.destroy();peer=null;}});p.on('disconnected',()=>{if(p===peer&&!p.destroyed){message('Reconnecting to the room service…');setTimeout(()=>{if(p===peer&&!p.destroyed)p.reconnect();},1500);}});return p;}
function hostGame(){reset();if(typeof Peer==='undefined'){message('Multiplayer could not load. Refresh, or play with bots.');return;}setBusy(true);message('Opening your room…');room=randCode();const p=setupPeer('kcw-v1-'+room);joinTimeout=setTimeout(()=>{if(!state){reset();message('Room service took too long. Try again, or play with bots.');}},15000);p.on('open',id=>{if(p!==peer)return;isHost=true;myId=id;state=newState();addPlayer(id,$('nickname').value);enter();});p.on('connection',conn=>{conn.on('open',()=>{if(!state)return;const reject=state.players.length>=MAX_PLAYERS?'This room is full (32 players). Ask chat to create another room.':null;if(reject){conn.send({type:'reject',text:reject});setTimeout(()=>conn.close(),400);return;}connections.set(conn.peer,conn);addPlayer(conn.peer,conn.metadata?.name);conn.send({type:'welcome',id:conn.peer,state:publicState()});broadcast();});conn.on('data',data=>{if(!state||!data||data.type!=='input')return;const pl=state.players.find(x=>x.id===conn.peer);if(pl){pl.inp={x:Math.max(-1,Math.min(1,Number(data.x)||0)),y:Math.max(-1,Math.min(1,Number(data.y)||0)),dash:!!data.dash};pl.lastInput=Date.now();}});conn.on('close',()=>{connections.delete(conn.peer);if(state){state.players=state.players.filter(x=>x.id!==conn.peer);arrange();broadcast();}});conn.on('error',()=>conn.close());});}
function joinGame(){const code=$('code').value.trim().toUpperCase();if(!/^[A-Z2-9]{6}$/.test(code)){message('Enter the 6-character code from your host.');return;}reset();room=code;if(typeof Peer==='undefined'){message('Multiplayer could not load. Refresh, or play with bots.');return;}setBusy(true);message('Finding room '+room+'…');const p=setupPeer();joinTimeout=setTimeout(()=>{if(!state){reset();message('Could not reach the host. Check the code, keep the host tab open, or try another network.');}},18000);p.on('open',id=>{if(p!==peer)return;myId=id;const c=p.connect('kcw-v1-'+room,{reliable:false,serialization:'json',metadata:{name:safeName($('nickname').value)}});hostConn=c;c.on('data',data=>{if(!data||p!==peer)return;if(data.type==='reject'){reset();message(data.text);return;}if(data.type==='welcome'||data.type==='state'){state=data.state;lastStateAt=Date.now();if(!document.body.classList.contains('playing'))enter();renderRoster();}});c.on('close',()=>{if(p!==peer)return;reset();message('The host closed the room. Create or join a new room.');});c.on('error',()=>message('Connection interrupted. Leave and rejoin, or try another network.'));});}
$('create').onclick=hostGame;$('join').onclick=joinGame;$('code').onkeydown=e=>{if(e.key==='Enter')joinGame();};
$('practice').onclick=()=>{reset();isHost=practice=true;myId='you';state=newState();addPlayer(myId,$('nickname').value);['Bump Goblin','Personal Space','Chat Menace','Yeet Machine'].forEach((n,i)=>addPlayer('bot'+i,n,true));enter();startRound();};
$('leave').onclick=()=>{reset();message('Room left. Ready for another?');};
$('copy').onclick=async()=>{const u=new URL(location.href);u.search='';u.hash='';u.searchParams.set('room',room);try{await navigator.clipboard.writeText(u.href);$('copy').textContent='LINK COPIED ✓';setTimeout(()=>$('copy').textContent='COPY INVITE LINK ↗',2200);}catch{message('Copy this invite: '+u.href);}};
function startRound(){if(!isHost||!state)return;if(state.players.length<2){message('Invite at least one friend to start. Or leave and try bots.');return;}state.phase='countdown';state.clock=3;state.radius=365;state.round++;state.winner='';state.players.forEach(p=>{p.alive=true;p.cool=0;p.boost=0;p.inp.dash=false;p.angle=0;});arrange();message('');broadcast();beep(300);}
$('start').onclick=startRound;
function publicState(){return {...state,players:state.players.map(({inp,lastInput,...p})=>p)};}
function broadcast(){if(!isHost||practice||!state)return;const msg={type:'state',state:publicState()};for(const c of connections.values())if(c.open)try{c.send(msg);}catch{}}
function renderRoster(force=false){if(!state)return;const signature=state.players.map(p=>p.id+p.alive+p.wins).join('|')+state.phase;if(!force&&signature===lastRoster)return;lastRoster=signature;$('count').textContent=state.players.length+' / '+MAX_PLAYERS;$('roster').replaceChildren();[...state.players].sort((a,b)=>b.wins-a.wins).forEach(p=>{const el=document.createElement('div');el.className='player-row';const dot=document.createElement('i');dot.style.background=p.color;const name=document.createElement('span');name.textContent=p.name+(p.id===myId?' (you)':'');const badge=document.createElement('small');badge.textContent=p.bot?'BOT':!p.alive?'OUT':'';const score=document.createElement('b');score.textContent=p.wins+' ★';el.append(dot,name,badge,score);$('roster').append(el);});$('start').hidden=!isHost||['play','countdown'].includes(state.phase);$('start').disabled=state.players.length<2;$('start').textContent=state.phase==='lobby'?"LET'S GOOOO!":'RUN IT BACK ↗';$('lobbyHint').textContent=isHost?(practice?'Bots are warming up with you. Invite real friends by creating a room.':'Keep this tab open—you host the room. Share the invite link with chat.'):'The host starts each round. Keep this tab open to stay in the room.';}
function moveInput(){if(mouseTarget&&state){const p=state.players.find(p=>p.id===myId);if(p){const dx=mouseTarget.x-p.x,dy=mouseTarget.y-p.y,n=Math.hypot(dx,dy);input.x=n<8?0:dx/Math.max(60,n);input.y=n<8?0:dy/Math.max(60,n);}}else if(!joystickActive){input.x=(keys.ArrowRight||keys.d?1:0)-(keys.ArrowLeft||keys.a?1:0);input.y=(keys.ArrowDown||keys.s?1:0)-(keys.ArrowUp||keys.w?1:0);}const n=Math.hypot(input.x,input.y);if(n>1){input.x/=n;input.y/=n;}input.dash=localDash;localDash=false;}
addEventListener('keydown',e=>{if(/INPUT|TEXTAREA/.test(e.target.tagName))return;if(['ArrowUp','ArrowDown','ArrowLeft','ArrowRight',' ','w','a','s','d'].includes(e.key)){e.preventDefault();mouseTarget=null;keys[e.key]=true;if(e.key===' '&&!e.repeat)localDash=true;}});addEventListener('keyup',e=>{delete keys[e.key];});addEventListener('blur',()=>{Object.keys(keys).forEach(k=>delete keys[k]);input.x=input.y=0;mouseTarget=null;joystickActive=false;});
function aimMouse(e){const r=canvas.getBoundingClientRect(),side=Math.min(r.width,r.height),left=r.left+(r.width-side)/2,top=r.top+(r.height-side)/2;mouseTarget={x:(e.clientX-left)/side*900,y:(e.clientY-top)/side*900};}
canvas.onpointerdown=e=>{if(e.pointerType!=='mouse'||!state)return;if(e.button===2){e.preventDefault();localDash=true;return;}if(e.button===0){canvas.setPointerCapture(e.pointerId);aimMouse(e);}};
canvas.onpointermove=e=>{if(e.pointerType==='mouse'&&e.buttons&1&&state)aimMouse(e);};
canvas.onpointerup=e=>{if(e.button===0){mouseTarget=null;input.x=input.y=0;}};
canvas.onpointercancel=()=>{mouseTarget=null;input.x=input.y=0;};
canvas.oncontextmenu=e=>e.preventDefault();
const joy=$('joystick');function joyMove(e){const r=joy.getBoundingClientRect(),dx=e.clientX-r.left-r.width/2,dy=e.clientY-r.top-r.height/2,n=Math.hypot(dx,dy),limit=r.width*.30;input.x=dx/Math.max(limit,n);input.y=dy/Math.max(limit,n);$('stick').style.transform=`translate(${input.x*limit}px,${input.y*limit}px)`;}
joy.onpointerdown=e=>{joy.setPointerCapture(e.pointerId);mouseTarget=null;joystickActive=true;joyMove(e);};joy.onpointermove=e=>{if(joystickActive)joyMove(e);};function releaseJoy(){joystickActive=false;input.x=input.y=0;$('stick').style.transform='';}joy.onpointerup=releaseJoy;joy.onpointercancel=releaseJoy;$('dash').onpointerdown=e=>{e.preventDefault();localDash=true;};
function simulate(dt){if(!state||!isHost)return;const me=state.players.find(p=>p.id===myId);if(me)me.inp={...input};if(state.phase==='countdown'){state.clock-=dt;if(state.clock<=0){state.phase='play';state.clock=0;beep(700);}return;}if(state.phase!=='play')return;state.clock+=dt;state.radius=Math.max(105,365-Math.max(0,state.clock-6)*5.5);
for(const p of state.players){if(!p.alive)continue;p.cool=Math.max(0,p.cool-dt);p.boost=Math.max(0,p.boost-dt);if(p.bot){const target=state.players.filter(q=>q.id!==p.id&&q.alive).sort((a,b)=>Math.hypot(a.x-p.x,a.y-p.y)-Math.hypot(b.x-p.x,b.y-p.y))[0];const edge=Math.hypot(p.x-450,p.y-450)>state.radius*.69;const tx=edge?450:target?.x||450,ty=edge?450:target?.y||450;const angle=Math.atan2(ty-p.y,tx-p.x)+Math.sin(state.clock*2+p.id.length)*.28;p.inp={x:Math.cos(angle)*.8,y:Math.sin(angle)*.8,dash:!edge&&!!target&&Math.hypot(target.x-p.x,target.y-p.y)<170&&Math.random()<dt*.9};}else if(p.id!==myId&&Date.now()-p.lastInput>500)p.inp={x:0,y:0,dash:false};
const inp=p.inp||{x:0,y:0},mag=Math.hypot(inp.x,inp.y);if(mag>.1)p.angle=Math.atan2(inp.y,inp.x);if(inp.dash&&p.cool<=0){p.vx+=Math.cos(p.angle)*700;p.vy+=Math.sin(p.angle)*700;p.cool=2.5;p.boost=.25;state.event++;state.eventText='WEEEEEEE!';}p.inp.dash=false;p.vx+=inp.x*1050*dt;p.vy+=inp.y*1050*dt;const drag=Math.exp(-3.6*dt);p.vx*=drag;p.vy*=drag;p.x+=p.vx*dt;p.y+=p.vy*dt;
if(Math.hypot(p.x-450,p.y-450)>state.radius+19){p.alive=false;state.event++;state.eventText=p.name+' went WEEEEEEE!';}}
const live=state.players.filter(p=>p.alive);for(let i=0;i<live.length;i++)for(let j=i+1;j<live.length;j++){const a=live[i],b=live[j],dx=b.x-a.x,dy=b.y-a.y,d=Math.hypot(dx,dy)||.01;if(d<46){const nx=d===.01?1:dx/d,ny=dy/d,overlap=(46-d)/2;a.x-=nx*overlap;a.y-=ny*overlap;b.x+=nx*overlap;b.y+=ny*overlap;const rel=(a.vx-b.vx)*nx+(a.vy-b.vy)*ny;const impulse=Math.max(100,rel*.94)+(a.boost>0||b.boost>0?180:0);a.vx-=nx*impulse;a.vy-=ny*impulse;b.vx+=nx*impulse;b.vy+=ny*impulse;}}
if(live.length<=1){state.phase='result';state.winner=live[0]?.name||'Nobody';if(live[0])live[0].wins++;state.event++;state.eventText='';beep(800,.35);broadcast();}}
function draw(t){ctx.clearRect(0,0,900,900);ctx.fillStyle='#17122d';ctx.fillRect(0,0,900,900);ctx.strokeStyle='#ffffff05';ctx.lineWidth=1;for(let x=0;x<900;x+=45){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,900);ctx.stroke();ctx.beginPath();ctx.moveTo(0,x);ctx.lineTo(900,x);ctx.stroke();}
const radius=state?state.radius:350+Math.sin(t/2000)*6;ctx.save();ctx.translate(450,450);ctx.rotate(t/14000);ctx.setLineDash([3,16]);ctx.strokeStyle='#79659a55';ctx.lineWidth=2;ctx.beginPath();ctx.arc(0,0,radius+27,0,Math.PI*2);ctx.stroke();ctx.restore();ctx.beginPath();ctx.arc(450,450,radius,0,Math.PI*2);const g=ctx.createRadialGradient(450,450,0,450,450,radius);g.addColorStop(0,'#221937');g.addColorStop(1,'#35234a');ctx.fillStyle=g;ctx.fill();ctx.strokeStyle=state?.phase==='play'?'#ff63b9':'#b493f0';ctx.lineWidth=6;ctx.shadowColor=ctx.strokeStyle;ctx.shadowBlur=28;ctx.stroke();ctx.shadowBlur=0;
ctx.save();ctx.beginPath();ctx.arc(450,450,radius-4,0,Math.PI*2);ctx.clip();ctx.strokeStyle='#ffffff08';ctx.lineWidth=1;for(let x=0;x<900;x+=50){ctx.beginPath();ctx.moveTo(x,0);ctx.lineTo(x,900);ctx.stroke();ctx.beginPath();ctx.moveTo(0,x);ctx.lineTo(900,x);ctx.stroke();}ctx.restore();
const demo=[{name:'YOU',color:COLORS[0],x:290+Math.sin(t/1000)*40,y:250+Math.cos(t/1300)*35},{name:'CHAT MENACE',color:COLORS[1],x:650+Math.sin(t/800)*36,y:385+Math.cos(t/1500)*100},{name:'NO TOUCHY',color:COLORS[2],x:335+Math.sin(t/1800)*100,y:660+Math.cos(t/1200)*30},{name:'WEEE!',color:COLORS[3],x:590+Math.sin(t/1300)*85,y:640+Math.cos(t/1100)*30}];
for(const p of state?state.players:demo){if(state&&!p.alive)continue;const r=23;ctx.globalAlpha=1;if(p.boost>0){ctx.strokeStyle=p.color;ctx.lineWidth=30;ctx.globalAlpha=.35;ctx.beginPath();ctx.moveTo(p.x,p.y);ctx.lineTo(p.x-Math.cos(p.angle)*70,p.y-Math.sin(p.angle)*70);ctx.stroke();ctx.globalAlpha=1;}ctx.shadowColor=p.color;ctx.shadowBlur=20;ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.strokeStyle='#ffffff80';ctx.lineWidth=2;ctx.stroke();ctx.fillStyle='#18132c';ctx.beginPath();ctx.arc(p.x+Math.cos(p.angle||0)*11,p.y+Math.sin(p.angle||0)*11,4,0,Math.PI*2);ctx.fill();if(p.id===myId){ctx.strokeStyle='white';ctx.lineWidth=2;ctx.setLineDash([4,4]);ctx.beginPath();ctx.arc(p.x,p.y,30,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);}ctx.font='bold 18px "DM Sans",sans-serif';ctx.textAlign='center';ctx.fillStyle='#ece4ff';ctx.fillText(p.name+(p.id===myId?' • YOU':''),p.x,p.y-39);}
if(!state)return;renderRoster();const me=state.players.find(p=>p.id===myId);$('dash').classList.toggle('cooldown',(me?.cool||0)>0);$('dash').innerHTML=me?.cool>0?me.cool.toFixed(1)+'<small>RECHARGING</small>':'WEEE!<small>DASH</small>';$('phaseLabel').textContent=state.phase==='play'?state.players.filter(p=>p.alive).length+' LEFT · '+Math.floor(state.clock)+'s':state.phase==='countdown'?'GET READY':state.phase==='result'?'ROUND '+state.round+' COMPLETE':'WAITING FOR PLAYERS';
const ann=$('announce');if(state.phase==='countdown')ann.textContent=Math.ceil(state.clock)||'GO!';else if(state.phase==='result'){ann.replaceChildren();const title=document.createElement('span');title.textContent=state.winner==='Nobody'?'DOUBLE WIPEOUT!':state.winner+' WINS!';const sub=document.createElement('small');sub.textContent=isHost?'Hit RUN IT BACK for a rematch.':'Waiting for the host to start a rematch.';ann.append(title,sub);}else if(state.phase==='lobby')ann.textContent='MAKE SOME ROOM.';else if(!me?.alive){ann.textContent='YOU WENT WEEEEEEE!';}else if(state.clock<1.4)ann.textContent='GO GO GOOOO!';else ann.textContent='';
if(state.event!==lastEvent){lastEvent=state.event;beep(350,.13);}if(!isHost&&Date.now()-lastStateAt>5000)message('Host connection paused. Keep the host tab in front, or leave and rejoin.');}
function frame(t){const dt=Math.min((t-lastFrame)/1000,.035);lastFrame=t;moveInput();if(state){if(isHost)simulate(dt);else if(hostConn?.open&&(t-lastSend>33||input.dash)){hostConn.send({type:'input',...input});lastSend=t;}if(isHost&&t-lastSend>50){broadcast();lastSend=t;}}draw(t);requestAnimationFrame(frame);}requestAnimationFrame(frame);
const codeFromURL=new URLSearchParams(location.search).get('room');if(codeFromURL&&/^[A-Z2-9]{6}$/i.test(codeFromURL)){$('code').value=codeFromURL.toUpperCase();$('join').textContent='JOIN ROOM';message('You’re invited! Pick your name and tap JOIN ROOM.');}
